import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";
import Navbar from "@/app/_component/Navbar";
import Footer from "./_component/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
